[features]
seeds = false
[programs.devnet]
mygif = "Ho9h78o7sZRrYuoFd9j8DFYUnwAcjYWVY2iJyDXxHpDX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/manhthong/.config/solana/devnet3.json"

[scripts]
test = "node tests/mygif.js"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
